version: "3"
services:
  web-frontend:
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env
    depends_on:
      - repo-manager-api
    volumes:
      - ./web/:/app
  repo-manager-api:
    build:
      context: ./repo-manager-service/
      dockerfile: Dockerfile
      target: repo-manager-api-dev
    ports:
      - "8000:8000"
    env_file:
      - ./repo-manager-service/.env
    depends_on:
      - qdrant-db
    volumes:
      - ./repo-manager-service/src/:/app/src
      - ./repo-manager-service/cloned_projects/:/app/cloned_projects
  llm-chat-api:
    build:
      context: ./llm-chat-service/
      dockerfile: Dockerfile
      target: llm-chat-api-dev
    ports:
      - "8080:8000"
    env_file:
      - ./llm-chat-service/.env
    depends_on:
      - qdrant-db
    volumes:
      - ./llm-chat-service/src/:/app/src
  qdrant-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./repo-manager-service/db_storage:/qdrant/storage
