name: Push Docker Images To Dockerhub

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Which service do you want to push? (web, repo-manager, all)'
        required: true
        default: 'all'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: gitchatsai
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Web service
      if: github.event.inputs.service == 'all' || github.event.inputs.service == 'web'
      uses: docker/build-push-action@v2
      with:
        context: ./web
        file: ./web/Dockerfile
        push: true
        tags: gitchatsai/web:latest

    - name: Build and push Repo Manager API service
      if: github.event.inputs.service == 'all' || github.event.inputs.service == 'repo-manager'
      uses: docker/build-push-action@v2
      with:
        context: ./repo-manager-service
        file: ./repo-manager-service/Dockerfile
        push: true
        tags: gitchatsai/repo-manager-api:latest
