name: Push Docker Images To Dockerhub

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Which service do you want to push? (web, repo-manager, all)'
        required: true
        default: 'all'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: gitchatsai
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        role-to-assume: ${{secrets.AWS_GITHUB_ACTIONS_ROLE_ARN}}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'

    - name: Build and push Web service
      if: github.event.inputs.service == 'all' || github.event.inputs.service == 'web'
      uses: docker/build-push-action@v2
      with:
        context: ./web
        file: ./web/Dockerfile
        push: true
        tags: |
          gitchatsai/web
          ${{secrets.ECR_REPO_URL}}/web

    - name: Build and push Repo Manager API service
      if: github.event.inputs.service == 'all' || github.event.inputs.service == 'repo-manager'
      uses: docker/build-push-action@v2
      with:
        context: ./repo-manager-service
        file: ./repo-manager-service/Dockerfile
        push: true
        tags: |
          gitchatsai/repo-manager-api
          ${{secrets.ECR_REPO_URL}}/repo-manager-api
        target: repo-manager-api-prod